#!/bin/sh

# Example for ~/.config/sxiv/exec/image-info
# Called by sxiv(1) whenever an image gets loaded,
# with the name of the image file as its first argument.
# The output is displayed in sxiv's status bar.

s=" | " # field separator

# Extract relevant information about the image
filename=$(basename "$1")
filesize=$(du -Hh "$1" | cut -f 1)
geometry=$(identify -format '%wx%h' "$1[0]")
format=$(identify -format '%m' "$1")
resolution=$(identify -format '%x %y' "$1[0]")

# Display the information
echo "${filesize}${s}${geometry}${s}${resolution}${s}${format}${s}${filename}"
